# This example config shows how to use Bitrise Pipelines
# to run multiple Android unit test shards in parallel

format_version: "11"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android

meta:
  bitrise.io:
    stack: linux-docker-android-20.04
    machine_type_id: elite

pipelines:
  pipeline_unit_test:
    stages:
    - stage_unit_test: { }

stages:
  stage_unit_test:
    workflows:
    - unit_test_app: { }
    - unit_test_library: { }

workflows:
  unit_test_app:
    envs:
    - MODULE: app
    - VARIANT: debug
    after_run:
    - _test

  unit_test_library:
    envs:
    - MODULE: lib-example
    after_run:
    - _test

  _test:
    steps:
    - git-clone: { }
    - android-unit-test:
        inputs:
        - module: $MODULE
        - variant: $VARIANT
