# This example config shows how to use Bitrise Pipelines
# to run Android unit and UI tests in parallel

format_version: "11"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android

meta:
  bitrise.io:
    stack: linux-docker-android-20.04
    machine_type_id: elite

pipelines:
  pipeline_unit_and_ui_test:
    stages:
    - stage_unit_and_ui_test: { }

stages:
  stage_unit_and_ui_test:
    workflows:
    - unit_tests: { }
    - ui_tests: { }

workflows:
  unit_tests:
    steps:
    - git-clone: { }
    - android-unit-test:
        inputs:
        - module: app
        - variant: debug

  ui_tests:
    steps:
    - git-clone: { }
    - android-build-for-ui-testing:
        inputs:
        - module: app
        - variant: debug
    - avd-manager: { }
    - wait-for-android-emulator: { }
    - android-instrumented-test: { }
